name: Arman
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - name: Build the data and create local changes
      uses: actions/setup-python@v1
      with:
        python-version: '3.11.7'
        architecture: x64
    - run: |
        pip install -r requirements.txt
        python process.py
